### ISSUE TITLE
Add simple HTTP Server for file exchange with desktop PC

### ISSUE THREAD

**Issue by mvitr** [MiniKeePass/MiniKeePass#152]
A simple, integrated HTTP Server would be great for exchanging files within a local wireless network. i.e. you start the server from within the app, the app shows you the url of the phone (ip:port) and you navigate to this url using the desktop browser, where you can download and upload the files
(I know several people who are not willing to provide their key files to dropbox!)

**Comment by Ciantic** [comment]
Reason this would be cool is because I can't trust a PC version of KeePass. Windows security is so bad, that it would be better to have iOS device as a KeePass *server*. 

Then I could keep the database only open on the iOS device and grant the access on demand to individual password/user requests, a HTTP server request compatible with KeePass Chrome addon.

**Edit** Worth to note, what I ask is different. I want HTTP server that is compatible with [ChromeIPass](https://chrome.google.com/webstore/detail/chromeipass/ompiailgknfdndiefoaoiligalphfdae) that communicates using [KeePassHttp](https://github.com/pfn/keepasshttp)
