### ISSUE TITLE
iOS 7.0.4 - error "Invalid file signature"

### ISSUE THREAD

**Issue by lenAchi** [MiniKeePass/MiniKeePass#250]
After update of iPhone 5 and iPad Air to iOS 7.0.4 no *.kdbx database can be open with MiniKeepass.
checked with the following Environment:
- Filestorage via Boxcryptor with Dropbox (combination used since > 12 months and works proper)
- iOS 6.x, iOS 7, iPhone 4S, iPhone 4, iPhone 5S, iPad 4, iPad Air
- MiniKeePass with UTF-8 Encoding
- Computer with KeePass (2.17, 2.24) on Windows 7
- language: German

Trails who not helped:
- deinstall and install of Minikeepass
- new database (file is not corrupt - works proper with KeePass (2.17, 2.24) on Windows 7)
- new database without keyfile
- new database with Keyfile

Can you help me?

**Comment by pretzelmonster** [comment]
Hello, I have the exact same issue since moving over from iPhone 5 to iPhone 6.
I get the Invalid File Signature error when I try to open my KDBX file (synced via Owncloud). This setup has worked before like a charm, but has stopped to work since the KDBX file has been updated and then synced to the iPhone.
Unfortunately lenAchis's advice didn't work (and also reinstall of MiniKeepass didn't work).

Any ideas?

Thanks!
