### ISSUE TITLE
Touch ID support with iOS 8?

### ISSUE THREAD

**Issue by dlong500** [MiniKeePass/MiniKeePass#321]
Can we get support for Touch ID authentication with iOS 8?  I've seen a variety of other apps implement it now that iOS 8 opens up the feature to third party apps.

Ideally I'd love to have support for Touch ID and a simple PIN so that I can avoid having to enter a complicated password but also be somewhat safe from fingerprint forgeries.

**Comment by tayfuuun** [comment]
+1 for Touch ID!

**Comment by ittaiz** [comment]
+1

**Comment by dargo1967** [comment]
Seems like just piling on at this point, but what the heck!  +1 for Touch ID!

**Comment by felipeogarcia** [comment]
Signed up for +1!

**Comment by PixelPaws** [comment]
Text for our App:

Hi,

first of all a big thank you to the Mini KeePass Developer. Great work.
We decided to take this App further and added functionalities that we ourselves wanted to see in the app to grant an awesome iOS user experience. We produced a new version modified with the following features (which we will add to in the near future). Currently implemented are

- In-App Local Wireless Sharing via Browser
- In-App FTP Sharing
- Touch ID
- Entries show expiration time

Link to App Store:
https://itunes.apple.com/us/app/keepass-touch/id966759076?mt=8&ign-mpt=uo%3D4

We will continue to focus on KeePass Touch and hope to bring you great new features.
We release two Versions of the App.
One with ads to help us with our expenses and if you want to support our cause you can get rid of them for 0,99$ and help us in bringing awesome features like 

- Callback URLs
- iOS 8 Extension for Safari -> password retrieving without opening the app
- changeable expiration time
- Auto FTP Sync on open database (based on file date) with option popup (overwrite yes/no)
- Custom Icons

and more to this great app!!!
We are even considering redesigning the whole interface to make it easier and more accessible and bring features like custom icons to KeePass Touch.
We hope you support our cause.


Best regards,

The People @ Pixel Paws

**Comment by dlong500** [comment]
@PixelPaws Regardless of how good of an app you have developed I don't think it's right for you to be advertising on some other project's forum (especially one that is open source when your app is not).  It's not good form, and especially doing in on Github's issue tracker for MiniKeePass causes a lot of confusion and obfuscates the information about issues with MiniKeePass.

I would consider removing this post to git rid of the confusion.

**Comment by 53245342099** [comment]
True that it wasn't good form to advertise this here.  On the other hand, there doesn't look to be much progress made on MiniKeePass during the last few months.  But on another hand, the developers say in their iTunes link that their version is open source.  Where is the source?  Their website is German only, and they don't seem to have any other apps on the app store.

**Comment by PixelPaws** [comment]
@dlong500 @53245342099 
Okay let me clear some issues here.

1. How could we reach you guys if not here, where you are registered and ask for some of those features in KeePass on iOS.
2. We are from Germany so our website is, of couse, in German. We will add an English version of our website soon.
3. The source code is available in the app currently via a mail delivering service that sends you the package of the projects contents.
4. If I get asked by the developer of Mini KeePass I will remove this post. No questions asked.

@53245342099 
There will be more apps from Pixel Paws soon. Stay tuned!

Best regards,

The Pixel Paws Team

**Comment by dlong500** [comment]
@PixelPaws Honestly, Reaching customers is your own job.  Linking to outside products in other company forums has always been a bad practice, and you are using the popularity of another competing (truly free) software product to try to attract customers to your paid product (your free version with ads isn't comparable to a true open source product).

Also, listing your app as open source and then saying you have to request a mail delivered "package" is highly unusual and reeks of deception.  At the very least you should have up-to-date source available for download on your website.  Since you have a Github account now (as of about a month ago), why don't you upload the source there and keep it updated?  I doubt that would happen though--I'm calling bull on the whole thing.  Your first release on the app store is yesterday.  It reeks of the leeches who package up other projects open source work and then try to charge for it.

If you hadn't approached things in this manner I might have actually paid for your app to check out the features you are touting, but I still would have waited a bit to see the history of development to make sure it didn't get abandoned with bugs and unresolved issues after the very first release.

To set things clear regarding true open source projects and the benefits, lets look at MiniKeePass since we're on their issue tracker already.  Regardless of when the last update was, we have the source code right here on Github and anyone could clone/fork the project.  So even if development from the original authors stops completely the project can still go on if there is interest in a very structured and easily accessible manner because of the Github platform.  A company that claims their software is open source but then makes people jump through hoops to get any version of the source (most likely outdated as well) is NOT the true spirit of open source (especially if it involves the company charging for a product).

**Comment by PixelPaws** [comment]
@dlong500
Because of the criticism you pointed at we removed the previous post. 
So to clear things up:

1. We didn't mean for any confusion. We apologize for the inconvenience.
2. We will finish a first update on the project soon as well as release new apps. So no worries.
3. We thought that GitHub takes a subscription fee from companies using Github repositories for commercial projects. So we decided not to move the source code here. As it is indeed free, we will provide the code via GitHub soon to push our effort to be more open-source. 
4. We didn't mean to leech anything but loved KeePass Mini on iOS and wanted to take it further and add great new features. 

We hope we can still provide you with a great experience and will continue our effort to improve KeePass on iOS so maybe you will change your mind and use our app.

Best regards,

Pixel Paws Team

**Comment by dlong500** [comment]
@PixelPaws 
Thanks for your response.  I hope you can produce a quality app.  Github is free for any public repositories even if you are charging money on the app store as far as I know, but if you hide the source code in a private repo then there is a fee.  Of course, a public repo with source available means that anyone can fork the code and remove any ads, so it isn't a great model for those wanting ad revenue.  If you have to get a revenue stream somehow on iTunes it would be better to just make the app 99 cents and be done with it and avoid all the advertisement mess to begin with.

But it would also be nice to contribute to a project like this if you have the experience and time to implement Touch ID support (via a repo clone and then submitting a pull request).  It could foster a lot of goodwill with users who might be willing to try out a different Keepass app for whatever reasons.  If you are going to be open source anyway then I would suggest consolidating around a project that has already been around for a while and trying find a different revenue source.

**Comment by wooster11** [comment]
+1 to what dlong500 has to say. You should definitely instead contribute to this project. 


On Mar 9, 2015, at 6:31 PM, dlong500 <notifications@github.com> wrote:

@PixelPaws 
Thanks for your response. I hope you can produce a quality app. Github is free for any public repositories even if you are charging money on the app store as far as I know, but if you hide the source code in a private repo then there is a fee. Of course, a public repo with source available means that anyone can fork the code and remove any ads, so it isn't a great model for those wanting ad revenue. If you have to get a revenue stream somehow on iTunes it would be better to just make the app 99 cents and be done with it and avoid all the advertisement mess to begin with.

But it would also be nice to contribute to a project like this if you have the experience and time to implement Touch ID support (via a repo clone and then submitting a pull request). It could foster a lot of goodwill with users who might be willing to try out a different Keepass app for whatever reasons. If you are going to be open source anyway then I would suggest consolidating around a project that has already been around for a while and trying find a different revenue source.

**Comment by jarush** [comment]
I'd like to thank those that took the time to respond to PixelPaws.  As one of the main developers for MiniKeePass, I want to go on record and say our issue pages is not an appropriate place to advertise your apps.

I'd also like to give people a heads up that we've implemented TouchId in the main repository, but we've been trying to test it throughly before we release an update.

I do not know when we will release a new version, since we are also working on some lock screen related changes that we'd like to get released in the next version.

**Comment by jarush** [comment]
We have a build we've been testing that includes Touch ID, a new PIN screen, and some enhanced security for storing PIN settings.  Using Apple's TestFlight service, we have made a beta version that we can invite user's to install and help us test these new features.

If you're interested in helping, send an email to minikeepass@gmail.com, and we'll send you a beta invite via Apple's TestFlight service.  All we ask in return is that you provide feedback on the new features and report any bugs you encounter.  I would also encourage anyone wanting to try the beta version to backup their KeePass files just in case.

**Comment by serkanaksu** [comment]
Hello jarush,

Touch ID ist working perfectly, I couldn't find any bugs. Just translations for the Touch ID unlock screen and PIN Unlock screen are missing.

Thanks for your hard work!

**Comment by jlk** [comment]
I emailed this feedback, but I'll leave it here as well: I really need the pin to be longer than 4 digits. I'm not sure if that is an IOS thing, or within MiniKeePass, but 4 digits is too cheap to crack for a password database.

**Comment by serkanaksu** [comment]
As far as I know it's just an app password, not an encryption password. For this you've got the db password. Correct me if I'm wrong!

**Comment by jlk** [comment]
Here's my current setup:

* Password db with a strong password
* MiniKeePass beta configured with...
  * TouchID configured
  * "Remember Database Passwords" enabled (I don't see point of TouchID without this)

Now - decrypt database, lock phone, unlock and go back into MiniKeePass. It presents TouchID authentication screen. Press "cancel." You're prompted for a 4 digit pin to access sensitive data that you originally had a more complex password on.

Perhaps I'm doing something wrong?

**Comment by wooster11** [comment]
I don't think you're doing anything wrong. I think that's by design at this
point.

It appears that TouchID is used for the PIN screen and not for database
unlocking.

Personally I feel that TouchID should instead be used for unlocking your
database and not unlocking the app; unless you're allowed to set up
something much more complex than a 4 digit pin to unlock the app. That
would make me much more comfortable using TouchID for the PIN along with
remembering database passwords.

**Comment by dlong500** [comment]
I haven't had a chance to test this yet but I agree that the only real point in a Touch ID feature is to avoid having to enter the complex database passwords every time.  Obviously this means the mechanism for MiniKeePass saving database passwords needs to be airtight to prevent security issues, and there definitely should be options for a more complex app password.

Assuming the app password was allowed to be more complex than a 4-digit pin, here are what I would like to see as options for authentication (in order of least secure to most secure):

1) Touch ID - OR - App password required (database password saved securely)

2) Touch ID - AND - App password both required (database password saved securely)

3) Touch ID - AND - App password both required, then prompt for database password as well

Obviously the options requiring Touch ID would only be available for devices that support it.  Also it would be good to get a brief summary of how the database password is saved without having to dive into the code.  How secure is this feature?  Is there any chance another process on the device could somehow get access to the cleartext password?

**Comment by wooster11** [comment]
The database passwords are saved using keychain which is provided by iOS.
So it's not an implementation made by MiniKeePass devs.

By doing this, the option of having that Keychain synchronized with iCloud
is available if you use it.

It looks like a bunch of documentation is available here on the security of
Keychain:
https://developer.apple.com/library/ios/documentation/Security/Conceptual/keychainServConcepts/02concepts/concepts.html

**Comment by ittaiz** [comment]
+1
Can't the Touch ID just be used for unlocking the database?
It just feels awkward to add yet another password in the mix

‏בתאריך יום שלישי, 24 במרץ 2015, Derek Woo <notifications@github.com> כתב:

**Comment by jarush** [comment]
There are a couple problems with trying to use Touch ID as an alternative to entering the KeePass database passwords.  One problem is how to secure the app and your KeePass file when the app is backgrounded, but still make it easy to resume where you left off when switching back to MiniKeePass (like when switching back/forth to copy/paste a password).

MiniKeePass currently keeps the KeePass file open when backgrounded and presents the PIN Screen/Touch ID to protect the app when resuming.  This is a simple way of protecting access to the app, and works with devices that don't support Touch ID (like my iPhone 5).  Additionally, the PIN Screen coupled with the Remember Passwords option is designed as an alternative to having to type a complex KeePass password that may be difficult on the device's keyboard, and that's why it uses a simple PIN.

It's possible to change how some of these features work, but the easiest way to add Touch ID without impacting other parts of the app is how it's currently implemented.

**Comment by wooster11** [comment]
You bring up some great points and I definitely agree with a lot of what you have to say. However, I still would like an additional feature added for an optional complex PIN as well.

For those of us who have Touch ID, we basically are trusting that the fingerprint hash is very difficult to replicate and that it's secure enough to lock down our database.

Based on the current beta and how I think users would like this to work, I think those with TouchID are expecting a workflow as follows:
1. Open MiniKeePass.
2. Use TouchID to proceed.
3. Now I see my database choices.
4. Select a database
5. See my passwords. No passcode necessary - we used TouchID already (in the case of the beta, to unlock the app).

Whether this is achieved by locking down the app with a PIN/passcode and storing your password on the keychain, or by using TouchID to unlock the database, I don't think that really matters that much. But based on your comments, I now understand why TouchID to unlock the actual database doesn't make too much sense - so I'm totally fine with using TouchID to instead unlock the app.

Now, I understand the problem of users without TouchID and the benefits of having a simple PIN (you basically want something that's nearly as easy to use as TouchID to get to your database). Simple PINs should definitely still be supported. But can't their be an option for a complex passcode as well?

Currently for unlocking our iPhones, iOS supports complex passcodes along with a simple PIN. In fact, my corporate iPhone has a policy on it that requires me to use a complex passcode to unlock it. Simple PINs are completely disabled. And because of this, I'm super happy I have TouchID - I'd hate having to enter my password every single time.

I feel like we should be able to have an option between a simple or complex PIN to unlock the app. If that gets added in, I think this feature is golden and I'd give high fives all around.

This feature could be an additional item in the settings under PIN protection (Use Complex PIN). If that's turned on, a new screen with the full keyboard comes up that requires you to enter a complex PIN to set.

**Comment by dlong500** [comment]
The issue is not about database passwords.  They will always need to be saved with keychain to avoid having to enter them each time.

If we can get the ability to have a complex passcode/PIN as well as having the option to require both Touch ID and the passcode that would be great.

The complex passcode by itself will especially help those without Touch ID who would still like to save the database passwords.

The ability to use BOTH Touch ID and passcode will add a layer of security for those wanting to have more than just Touch ID authentication without having to enter all the database passwords as well.  In my case, I'd use Touch ID along with a relatively simple passcode just for a little bit of extra security to protect against fingerprint spoofing.

**Comment by jlk** [comment]
Just noticed the beta's expired. :(

**Comment by jlk** [comment]
And looks like there's something seriously wrong when I return to the latest MiniKeePass in the app store:

* I was using TouchID with the beta release, db password saved in keystore
* Upon switching back to the app store version, MiniKeePass is not asking for password to decrypt db, even though "Remember database passwords" is not enabled under settings
* After enabling and then disabling "Remember database passwords," killing the app and restarting, it then asked for db password.

Seems like something worth double-checking...

**Comment by claym** [comment]
Yeah, I would love to get an updated version of this. Any info from the
devs?

**Comment by jlk** [comment]
I see a updated version of the beta pushed out, thanks. Alas, I'm getting this error when I try to renew the app in TestFlight:

```
The app couldn't be installed because the profile has expired. Try again
```

...I can't quite figure out if that's a issue for the user or dev to fix. Looks like some things changed for TestFlight on IOS8...

**Comment by almson** [comment]
Just dropped in to say @dlong500 was wrong for what he did. Besides being very impolite to the point of being offensive (can't we all just get along?), I disagree that it's "bad practice" to link to a competitor. Let me explain. It increases competition, which is a good thing. Newegg does not want people on its forums linking to Amazon or Ebay because Newegg's self-interest is in suppressing competition and making more money. Even an open-source developer may want to suppress competition and have his app be more popular. Yet competition is good. It's fine to go on an issue tracker where everyone is complaining about a missing feature and say, "my app has this feature," as long as it's done in good faith (not a scam), the other app is half-decent, the message is one-time, etc. It's fine because it possibly helps the other visitors find a better product (even if this product's owner/developer/fanboy hates it and wants to hoard all users). It also doesn't matter if the other app costs money or its developers are confused about what being open-source means. (And everyone wins when they come here and we correct them and encourage them to be better.)

**Comment by dlong500** [comment]
@almson Nice troll, but I'll bite anyway.  I think most people here would agree that your post is far more "offensive", and your logic is way off base.  It is pretty much universally regarded as bad practice to link to ANY other software in a support forum as it is simply not related to the software at hand.  It makes it even worse when the whole point of the post is to say "My software has this feature so come use it instead of this software".  I'm not sure what planet your living on considering that MiniKeePass is a completely open source and free software so to implicitly accuse them of wanting to "hoard" users is as funny as it is ridiculous.  What exactly is your comment contributing to this discussion especially if you claim to have a "can't we all just get along" mentality?

In any case, I was actually quite reasonable in my response, and wished PixelPaws well in his development especially if he eventually open sourced his app (as was his claim).  Let's please keep this discussion pertinent to MiniKeePass and it's efforts for TouchID.
