### ISSUE TITLE
Any plans for an Offline Version?

### ISSUE THREAD

**Issue by sighh** [MiniKeePass/MiniKeePass#330]
The Keepass2Android app has two versions - one that has internet access and one without.  I'm using Keepass2Android Offline for my android phone.  I'd really like to have a similar option for my ipad.  Are there any plans to implement a 2nd version of the MiniKeePass app without internet access?  If not, is there a way to deny the app internet access in the same manner that we can deny apps location access, etc?

**Comment by miknuc** [comment]
Technically this is correct, you can do this with dropbox/owncloud/box/...

 However, it is a complex and error prone process 
- to open the app (owncloud in my case)
- navigate into the right directory
- refresh the file
- send the file to minikeepass
- in minikeepass open the right file again
- (now comes the usual keepass stuff)
- after changing something, export the file back to the owncloud app
- ensure that it is synchronized correctly

7 manuals steps. I tried to to explain this to my wife. Which was hard for me, because I hardly could remember these steps after a few weeks. Then she asked: on my android phone with keepass2android I simply open the app, enter my password and the app does all this IT stuff. Why can't I have the same for my Ipad?

In my eyes, this missing functionality is really a major disadvantage. I even consider to put kdbx files back on dropbox and use one of these closed source apps for IOS. I really would like to avoid this for security reasons, but with this lack of synchonization feature MiniKeePass is no app I would use regularily. 

I would really appreciate if you could consider this synchronization feature a useful enhancement that is worth the effort to be implemented.

**Comment by ittaiz** [comment]
+1

**Comment by BasicXP** [comment]
The app allows the user to upload databases and key files through iTunes.

Also, the application itself does NOT do any Internet data transfers itself — they're done by other applications via iOS APIs if requested by the user.

And finally, if you don't trust your encrypted database to Dropbox or any other service, then your master password just isn't good enough :)

**Comment by sighh** [comment]
Thanks @BasicXP !

I'm a huge fan of the app not having internet access.  Makes me feel better about putting my info in the app and on my device.  I don't fully trust those LastPass, 1Pass, etc cloud based programs.

**Comment by sighh** [comment]
Though I am confused about how it manages to have an integrated web browser without an internet connection.

**Comment by jarush** [comment]
The integrated browser can access the Internet.  It uses Apple's UIWebView widget which handles all networking, and is only active when actually using the integrated browser.  If you disable the integrated browser setting, the app does not perform any networking.  We have no plans to release a version of the app without the integrated browser.

**Comment by sighh** [comment]
Thank you @jarush for that explanation.
