### ISSUE TITLE
I  have accidentally cancelled the Mini KeePass application on my Iphone

### ISSUE THREAD

**Issue by Avesani** [MiniKeePass/MiniKeePass#363]
I  have accidentally cancelled the Mini KeePass application on my Iphone.
How can I retrieve my passwords? I have uploaded a backup from last month, I got back the application but it is empty.
Thanks

**Comment by jarush** [comment]
Did you have a backup of you kdb/kdbx file? If so, you can use iTunes to copy the file back into MiniKeePass.

If you only had a backup of the MiniKeePass ipa file (the app itself), that won't contain your passwords.

If you have a backup of your phone (in iTunes for example), you could try restoring the backup onto your phone. This should restore the password file itself, but it will reset any changes on your phone since the backup.

**Comment by Avesani** [comment]
Thanks Jarush. I do not have a kdb backup :(. I tried uploading an iphone backup and it seems that it uploads just the app, empty without any password.
Do you know how can I reach the developer who created the app and get back my password?
Thanks

**Comment by wooster11** [comment]
Jason/Jarush is actually one of the developers of the app. 

His suggestions were all sound. If you didn't back up your kdb somewhere, you may be out of luck.
