### ISSUE TITLE
iOS 9 slide over support for iPad

### ISSUE THREAD

**Issue by timothythlau** [MiniKeePass/MiniKeePass#407]
Would be awesome to add slide over support for iPads. Would allow for an easier way to copy/paste login credentials from the slide over menu without quitting the current app.

**Comment by cookies4breakfast** [comment]
Bumping this thread in the hopes that it'll get noticed. This  **needs** to be implemented especially when every other password management app on iOS has this feature. The devs have not updated the app since July and it makes me wonder if they even know or care. It sucks that there is no way to contact them directly.

**Comment by genkobar** [comment]
Hi all,

I'm not one of the original developers, but I saw that support for this feature could be added relatively easily.

However, I don't have an iPad that supports slide over so I was only able to test this in the iOS simulator. It would be very helpful if someone could try to build my branch in Xcode and see if it works without any problems.

BTW, this branch also enables upside-down orientation for all devices, which I'm sure the original developers want to take into consideration.

**Comment by adrianmoisey** [comment]
I'll build and test it on my iPad Air 2. 
I've never done this before, so I may need help.

I'm busy downloading Xcode, I'll let you know if I get stuck.

**Comment by genkobar** [comment]
Great!

When I was first trying to build MiniKeePass myself, I got a bit tripped up on the MBProgressHUD sub-project requirement. You'll need to download it separately and integrate into the project (basically drag-&-drop and edit some project settings) according to the instructions: https://github.com/MiniKeePass/MBProgressHUD

**Comment by adrianmoisey** [comment]
Ah thanks, I also got stuck on that.
I've managed to get it running in a simulator, I can't figure out how to build it against my iPad. Do I need a developer account for that?

**Comment by adrianmoisey** [comment]
If I select my iPad from the dropdown, and click the "play" button, I get "Could not find Developer Disk Image"

**Comment by jarush** [comment]
@adrianmoisey I'm not sure about that specific error, but I believe you'll need a developer license to run it on your iPad.

**Comment by adrianmoisey** [comment]
That would make sense.

I tested out the latest Minikeepass on my iPad, it does indeed have slide-over and split-view already.

I think it's safe to close this issue.

**Comment by tripplet** [comment]
Just to clarify this, you can put apps to your own device for debugging for free (given you have a mac), but the developer certificate is limited to 7 days, so it's sadly only feasible for debugging as you have to reapply the app to the device every 7 days :smile:.

It was 90 days when apple started this "free" program but, they reduced it to 7 (probably because of misuse)

**Comment by genkobar** [comment]
@adrianmoisey Glad to hear slide-over and split-view is already supported.

@timothythlau @cookies4breakfast Does it work correctly for you guys?

**Comment by timothythlau** [comment]
Yup working great here. Thanks again!
