### ISSUE TITLE
Touch ID only unlock the app, but DB is still locked

### ISSUE THREAD

**Issue by masutomo** [MiniKeePass/MiniKeePass#490]
Hi Developers,

I don't know it is a bug or feature. But when I unlock the app by touch id, it shows the DB selection screen, and it still ask me the password to unlock the DB file. Is it by design? I suppose using touch ID can access the DB records directly without asking further authorization.

FYI. I'm using iphone 7 & ios 10.3.
Thanks.

**Comment by tssmith7** [comment]
@masutomo, it is by design, I think and there are several settings that change the behavior.

The "Pin Protection", and "Close Database on Timeout" sections are the ones you need to worry about.

You can require pin/touchID and require a database password every time you go into MiniKeePass (pin enabled=YES, Lock timeout=Immediate, close timeout=Immediate)
You can only require a pin/touchID and leave the database open if left that way (pin enabled=YES, lock timeout=Immediate, close enabled=NO) 
You can require a pin/touchID and close the database and require a password after a set time limit (pin enabled=YES, Lock timeout=Immediate, close timeout=5 min)

Note that you can also have MiniKeePass remember the database passwords in the secure keychain on your iPhone.  If you enable that setting then it will not ask you for your database password when you open it (after the first time).

It is currently possible to turn off "pin protection" and "close database on timeout" which means that you could leave you database open forever without requiring a pin or password.  This may be a bug.

It is also possible to turn off "pin protection" and turn on "remember passwords" which means that you can open a database without requiring a pin or password.  This also may be a bug.

**Comment by masutomo** [comment]
Hi, thanks for your reply.

After I tried your 2nd suggestion (pin enabled=YES, lock timeout=Immediate, close enabled=NO), it's in fact does not close the DB after touchID unlock. But now it requires unlock on every task switching to the app. Usually my use case is:
1) copy the username in keepass
2) switch to the target app, paste once,
3) switch back to keepass, copy password
4) switch to the target app, paste the password

so it is now require 1 more touch ID unlock during step 3. A bit troublesome but i'll accept this compromise. It is still better than unlock the DB by typing the ultra long password again. :)
And I don't like to save the DB password in the secure keychain either. ^.^

Maybe I wish there is an option to allow me to use the DB for a few mins (e.g. PIN=Yes, Lock timeout=5 mins, Close Enable=NO) without asking for any unlock during that 5 mins, then lock the app but not close DB after 5 mins.

Thanks again!

**Comment by tssmith7** [comment]
@masutomo you can do just what you need by using the settings you proposed. It is possible to set "Lock Timeout" to longer than "Immediately" and it will work as you desire.
