### ISSUE TITLE
Version 1.7 iOS11 crash

### ISSUE THREAD

**Issue by mmalinin** [MiniKeePass/MiniKeePass#510]
App crashes while opening database with key and saved password. Before update it worked perfectly without problems.

**Comment by hcarrega** [comment]
ITs happening the same after passdw and key it force closed

**Comment by thvoe** [comment]
App crashes if you try to select a keyfile (I don't use the standard databasename.key).

**Comment by thvoe** [comment]
Is there any kind of workaraound?
I have important data on my mobile while I'm travelling around!

**Comment by jarush** [comment]
Since the couple password databases I tested don’t crash on my device, could someone that’s reported this issue send me a sample database that crashes? Just email me a simple kdb file with no personal information, along with the password and keyfile and I’ll be able to debug the issue. You can send it to jarush (at) gmail (dot) com. Thanks.

**Comment by jarush** [comment]
Thanks for reporting this issue.  We're currently tracking it in issue #526.  We will try and get 1.7.2 in the app store soon, and if that doesn't fix it please open a new issue.
