### ISSUE TITLE
Version 1.7 crashes after pw entered on IOS 10.3.3 and Iphone 5

### ISSUE THREAD

**Issue by jhwrage** [MiniKeePass/MiniKeePass#514]
Before the last update everything was fine. Now MiniKeePass crashes after opening an kdb v2 file with password.

**Comment by Bollekes** [comment]
I've the same proble on an Iphone SE

**Comment by dbush2017** [comment]
Same problem on iPhone 6s

**Comment by gabox7** [comment]
Opening a KDBX causes a crash ver 1.7.1 iphone 6s+ ios 10.3.3 Please any solution ? thanks in avance.

**Comment by jarush** [comment]
Since the couple password databases I tested don’t crash on my device, could someone that’s reported this issue send me a sample database that crashes? Just email me a simple kdb file with no personal information, along with the password and I’ll be able to debug the issue. You can send it to jarush (at) gmail (dot) com. Thanks.

**Comment by gabox7** [comment]
mmm how strange. now i dont have a DB empty. All have real information and password.I see I'm not the only one with this problem. Maybe someone else can pass you a DB for testing. TIA!

**Comment by Erreu** [comment]
It might be related to an entry with a blank title? https://github.com/MiniKeePass/MiniKeePass/issues/537#issuecomment-333430017

**Comment by jarush** [comment]
Thanks for reporting this issue.  We're currently tracking it in issue #526.  We will try and get 1.7.2 in the app store soon, and if that doesn't fix it please open a new issue.
