### ISSUE TITLE
KeepassXC Files Can No Longer be Opened

### ISSUE THREAD

**Issue by Ifhalted** [MiniKeePass/MiniKeePass#663]
Tried to open a file saved in the most recent version of KeepassXC (2.4.0), and the iOS Minikeepass reports that it cannot open the file. Tried the file in Keepass Touch, and it opens without issue.

**Comment by Kugelfang666** [comment]
same problem with me

**Comment by dukeofunk** [comment]
3rd. After sync, MiniKeepass fails to open .kdbx -- Error Could not open database
Import repair in KeePass did not correct.

**Comment by aakay** [comment]
Can confirm (iOS 12.2 & KeepassXC 2.4)

**Comment by dukeofunk** [comment]
Confirmed. iOS 12.2 and KeePassXC 2.4, the issue continues.

Regards

**Comment by sseneca** [comment]
Can confirm this happens with me as well. I suspect it's because of a bug in KeePassXC to do with the database format (for me at least) -- here is the related bug report:

https://github.com/keepassxreboot/keepassxc/issues/2948

Edit:

That didn't take long! It seems the KeePassXC developers are unwilling to fix this issue, so for now using MiniKeePass and KeePassXC in conjunction is no longer possible.

Possible solutions:

- Use KeePassX instead (not sure if this still supports v3.1?)
- Move to another iOS app and use KDBX v4
